# Generated by Django 5.1.3 on 2025-01-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_moviehitchart_remove_moviemanage_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviehitchart",
            name="BoxOffice",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="moviemanage",
            name="year",
            field=models.IntegerField(null=True),
        ),
    ]
