# Generated by Django 5.1.3 on 2025-01-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_moviehitchart_boxoffice_moviemanage_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviehitchart",
            name="Budget",
            field=models.IntegerField(null=True),
        ),
    ]
