# Generated by Django 5.1.3 on 2025-01-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_moviehitchart_budget"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieDB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=100)),
                ("year", models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="MovieManage",
        ),
    ]
